sudo: false

addons:
  postgresql: "9.3"
  apt:
    packages:
      - pkg-config
      - libcairo2-dev
      - libjpeg8-dev
      - libgif-dev

env:
  - NPROCS=1 JOBS=1 PGUSER=postgres

language: node_js
node_js:
  - "0.10"
