before_install:
  - sudo apt-add-repository --yes ppa:mapnik/v2.1.0
  - sudo apt-get update -q
  - sudo apt-get install -q libmapnik libmapnik-dev postgresql-9.1-postgis libsigc++-dev

env:
  - NPROCS=1 JOBS=1

language: node_js
node_js:
  - 0.8
