sudo: false

language: node_js

node_js:
  - "12"

jobs:
  include:
    - env: POSTGRESQL_VERSION="10" POSTGIS_VERSION="2.4"
      dist: xenial
    - env: POSTGRESQL_VERSION="11" POSTGIS_VERSION="2.5"
      dist: xenial
    - env: POSTGRESQL_VERSION="12" POSTGIS_VERSION="3"
      dist: bionic

install:
 - npm ci

script:
  - if [[ $POSTGRESQL_VERSION == '10' ]]; then sudo add-apt-repository -y ppa:cartodb/gis; fi;
  - sudo add-apt-repository -y ppa:cartodb/postgresql-$POSTGRESQL_VERSION
  - sudo apt-get -q update
  - sudo apt-get install -y --allow-unauthenticated --no-install-recommends --no-install-suggests postgresql-$POSTGRESQL_VERSION postgresql-client-$POSTGRESQL_VERSION postgresql-server-dev-$POSTGRESQL_VERSION postgresql-common postgresql-$POSTGRESQL_VERSION-postgis-$POSTGIS_VERSION postgresql-$POSTGRESQL_VERSION-postgis-$POSTGIS_VERSION-scripts postgis
  - sudo pg_dropcluster --stop $POSTGRESQL_VERSION main
  - sudo rm -rf /etc/postgresql/$POSTGRESQL_VERSION /var/lib/postgresql/$POSTGRESQL_VERSION /var/ramfs/postgresql/$POSTGRESQL_VERSION
  - sudo pg_createcluster -u postgres $POSTGRESQL_VERSION main --start -p 5432 -- --auth-local trust
  - npm test

after_failure:
  - pg_lsclusters
  - sudo cat /var/log/postgresql/postgresql-$POSTGRESQL_VERSION-main.log
