addons:
  postgresql: "9.3"

env:
  - NPROCS=1 JOBS=1 PGUSER=postgres

before_install:
 - sudo add-apt-repository -y ppa:cartodb/cairo
 - sudo apt-get update
 - sudo apt-get install -y pkg-config libcairo2-dev libjpeg8-dev libgif-dev
 - sudo add-apt-repository -y ppa:fkrull/deadsnakes
 - sudo apt-get update
 - sudo apt-get install -y python2.7

language: node_js
node_js:
  - "0.10"

notifications:
  irc:
    channels:
      - "irc.freenode.org#cartodb"
    use_notice: true
